### ISSUE TITLE
The Rex Layout

### ISSUE THREAD

**Issue by dstarck-infuse** [pixaura/cliqrex-main#127]
The Rex :
- displays entertainment items based on the "Freshness Algorithm" (see card- The Rex Freshness Algorithm - Beta) #130 
- on initial display ALL is 'selected / active' and all types of media are to be displayed in the feed : TV Shows, Movies, Podcasts
- active filter is underlined

Functions:
- User Can : select a filter (TV, Movies, Pods) which will sort / filter the list of cards displayed to the user
- User Can : Select Explore Cliq Rex - which will display drop down detailing the 4 options :CliqRex, AppRex, GlobalRex, ListRex -and associated short description text for each dropdown item
dropdowns : Cliq Rex - Filter Dropdown #128 
- User Can : Select the media filters (to the right of 'explore cliq rex' ) - which will display the media filter modal overlay.
media filters modal overlay : Media Filters - modal overlay #129 

Attachments:
- Default ALL Rex initial State
- Rex_filter: show state after users refines display to TV Shows, Movies or Posdcasts
- Rex_filter_global : shows state after user selects global Rex which will include 'non cliq' users in the display

![image](https://user-images.githubusercontent.com/101785604/171945442-df1c5b68-18db-45a4-a786-2da40b3b9dc3.png)

![image](https://user-images.githubusercontent.com/101785604/171945485-84824f29-0d31-49df-a465-36b9fddf0cfe.png)

![image](https://user-images.githubusercontent.com/101785604/171945514-626c4a4e-cc63-4dbc-bc79-3502603be583.png)

**Comment by palepinkdot** [comment]
Currently blocked by #129 #128 (which currently has no information), and #132?

**Comment by palepinkdot** [comment]
Items are the top are designed as "tabs" not as like filter options. So are there tabs for different screens containing the different types or are these supposed to function as checkboxes?
