### ISSUE TITLE
User Recommendations: Filter Dropdown

### ISSUE THREAD

**Issue by dstarck-infuse** [pixaura/cliqrex-main#128]
The Rex Dropdown 
-currently defaults to CliqRex.

Functions:
After clicking the dropdown selector the drop down menu is displayed just beneath the drop down component
- User Can : Select Explore Cliq Rex - which will display drop down detailing the 4 options :CliqRex, AppRex, GlobalRex, ListRex -and associated short description text for each dropdown item

--CliqRex
What’s trending with your friends

--AppRex
What’s trending within the app

--GlobalRex
What’s trending globally

--ListRex
Trending lists inside the app

This will help users that have not created any cliqs to explore what's happening on CliqRex.

Attachments:
- Dropdown with highlighted 'active' filter
- Dropdown overlay on stage should be located 10px below the dropdown trigger

![dropdown__explore_cliq_rex](https://user-images.githubusercontent.com/15748883/173118199-97640409-8b0b-4f41-84fb-ec6e515663a5.png)
![cliq_rex_filter_dropdown](https://user-images.githubusercontent.com/15748883/173118215-76a8baf3-1013-407c-8ba9-6bf76aa9a319.png)

**Comment by palepinkdot** [comment]
Once unblocked please change labels.

**Comment by BobRoman** [comment]
Hey Max - just  ported this over from the original Trello board - let me know if you have any questions.
