### ISSUE TITLE
The Rex sort by most recent

### ISSUE THREAD

**Issue by dstarck-infuse** [pixaura/cliqrex-main#130]
Description:
As a CliqRex user, when I load TheRex screen I want to see a list of media items that have been **rated** and Commented on by members of my **friends list** (in order of most recent/freshest descending) so that I can see the most recent activity at the top of my feed.

Acceptance Criteria:
- Initial Display should default to CliqRex and display cards that have recently been **rated** or Commented on by people in my Cliq
- Selecting CliqRex should display cards that have been recently **rated** or Commented on by people in my Cliq
- Selecting AppRex should display cards that are trending within the app as a whole (including users outside my Cliq)
- Selecting GlobalRex should display cards that trending globally outside the app via 3rd party network ratings
- Selecting ListRex should display lists that are trending within the app based on the number of Follows to that specific list (currently starred) (including users outside my **friends list**)

Exceptions:
[A list of exceptions to the Acceptance Criteria.]

Related Issues:

- #127

**Comment by palepinkdot** [comment]
Updated title to reflect actual requirements of the feature, this is not an algorithm.

**Comment by palepinkdot** [comment]
Why is #134 related?

**Comment by palepinkdot** [comment]
Good news: was pulling entire document instead of just the id, so we're all good to sort by date modified, will be finished by lunch and since this is an API change it will be available for testing today!

**Comment by palepinkdot** [comment]
Things that qualify as an update to a media:

- Rating
- Updating rating
- Commenting
- Replying to a comment
- Changing watch status
