### ISSUE TITLE
Main media filters not functioning

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#146]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

iPhone 11 iOS 15.5

### Expected Behavior

As a user, I want to filter my Rex by TV, Movie, or Podcast and only see that media type.

### Actual Behavior

The filters are not restricting the media types displayed - when I have only Movie selected, I am still seeing TV; when I have only Podcasts selected, I still see movies; etc.

### Steps to reproduce

1. Go to Rex
2. Select only the Movie filter
3. scroll through list

### Screenshots

![](https://trello.com/1/cards/62b0c3747bdda30fa39b6d8f/attachments/62b0c5d4d3f61448afc57853/previews/62b0c5d5d3f61448afc5786c/download/2689A904-CDF4-4F67-B024-1CBAB4DB1483_1_105_c.jpeg.jpg)

**Comment by palepinkdot** [comment]
Cannot reproduce.
![image](https://user-images.githubusercontent.com/55257671/175047665-a7ece28f-ea53-47db-b628-62d876944401.png)
![image](https://user-images.githubusercontent.com/55257671/175047736-328f9dae-6c85-477a-9c26-fbbf7ecf276d.png)
The shows listed are all movies.

Furthermore API response shows only movies: 
![image](https://user-images.githubusercontent.com/55257671/175048064-36ffe788-13de-446c-92ef-cd0e66cac1d3.png)
