### ISSUE TITLE
New MyCliq Layout

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#155]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CliqRex user I want to see my friends and search for new friends in MyCliq

### Acceptance Criteria

- user should be able to search for new friends within the app
- initial display should default to displaying your friends that you follow 
- user should be able to toggle the display and show users that are following them (active user)
- user should be be shown new users that are not their friends but have a high affinity

### Exceptions

none

### Related Issues (if applicable)

- #156
- #157 
- #158 
- #160

### Screenshots

![MyCliq – v1](https://user-images.githubusercontent.com/15748883/176552358-10a53a4d-e766-480b-a22a-4f5073b5f62d.png)
![MyCliq – v1 - followers](https://user-images.githubusercontent.com/15748883/176552371-9056c75a-7dda-4a2a-ab10-4353b8c420a5.png)

**Comment by palepinkdot** [comment]
Fixed by #160
