### ISSUE TITLE
MyCliq - Default Display Friends

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#156]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CliqRex user when I load the MyCliq the screen should default to showing me 8 of my friends with the highest level of affinity to me.

### Acceptance Criteria

- [x] on initial load screen defaults to MyCliq ~~(and should be underlined)~~
- [x] up to 8 friends are displayed
- [x] clicking on any individual user should take you to their profile page
- [x] User should be able to toggle between MyCliq and People That Follow Me
- ~~display order should be determined based on affinity (highest affinity top left, lowest bottom right)~~
- ~~Show All functionality should link user to MyCliq - Show All Screen~~ 

### Exceptions

none

### Screenshots

![Filter_MyCliq](https://user-images.githubusercontent.com/15748883/176553253-17943063-a7b0-43e2-ace6-ac6cf85aa562.png)

**Comment by palepinkdot** [comment]
> Show All functionality should link user to MyCliq - Show All Screen 
> display order should be determined based on affinity (highest affinity top left, lowest bottom right)

Changed acceptance criteria to not depend on a "child issue." Removed sorting by affinity, this would require pre-fetching affinity which we're not going to do because it would be totally unreasonable and expensive to query 8 full loaded users each time a user logs in.

**Comment by palepinkdot** [comment]
![image](https://user-images.githubusercontent.com/55257671/176712235-06fcee07-e89c-4bc7-851d-6bfea2048807.png)
