### ISSUE TITLE
Sign in with Google Crashes App

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#164]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

iOS 15.3.1

### Last Known Working CliqRex version

never

### Expected Behavior

The app should allow me to login via my Google Acct. 

### Actual Behavior

App  Crashes 

### Steps to reproduce

Logout of App (or start fresh) 
Click Sign in with Google
App Crashes

### Screenshots

https://user-images.githubusercontent.com/15748883/177558892-4c658b8b-557a-4150-9a8a-2753a28c9056.mp4

### Additional information

#151

**Comment by palepinkdot** [comment]
Cannot reproduce on Android

**Comment by palepinkdot** [comment]
Fixed. Firebase URL changed for some reason.
