### ISSUE TITLE
Error loading People that follow me tab

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#166]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.3.1

### Last Known Working CliqRex version

n/a

### Expected Behavior

When clicking on people that follow me I should see users that follow me.

### Actual Behavior

- I do not see users that follow me
- presented with an error screen

### Steps to reproduce

1. click myCliq
2. click People that follow me
3. see error

### Screenshots

https://user-images.githubusercontent.com/15748883/177572360-22e58679-2525-4a43-8521-1fbf4833b422.mp4

**Comment by palepinkdot** [comment]
Not a bug, you managed to add a user that doesn't exist, probably James.
