### ISSUE TITLE
Feed items appear to not be updating after event

### ISSUE THREAD

**Issue by palepinkdot** [pixaura/cliqrex-main#17]
From cliqrex-app created by [palepinkdot](https://github.com/palepinkdot): pixaura/cliqrex-app#16  

only details:

I added a show and it doesn't show up in Dara's feed.

**Comment by palepinkdot** [comment]
@stuffthatspins

When did you rate it?
What screen did you rate it on?
What show was it?

**Comment by stuffthatspins** [comment]
rated from feed or rex
rated on rex screen
show was shawshank redemption 
stored it in my list, G.O.A.T.
