### ISSUE TITLE
User Profile - Non Cliq Member

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#174]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CliqRex user, I want to be able to view another user's profile, including details and lists. If they're not in my Cliq I can add them to my Cliq.

### Acceptance Criteria

- User Profile should display user image with affinity ring, name, username, affinity match % (written out), about/info, and social links if added.
- User Profile can be shared.
 -Lists will include Top Lists (Top TV Shows, Top Movies, Top Podcasts), Followed Lists, Custom Lists, and Followed Lists for the user you're viewing.
- All lists will be formatted the same.
- Media items in the list are left-right scrollable
- Media items are sorted by HIGHEST RATING first in Top Lists
- Media items are sorted by NEWEST item first in

**Custom Lists**
-Media items display the user that you're viewing's ratings. Since this user is not in Cliq, ratings are in grey
-Media items are clickable to the detail card
-Custom Lists and Followed Lists can be shared (video says Favorited but going with Followed).

### Exceptions

- Custom and Followed Lists can be followed. An empty star shows it’s not being followed. A filled in (yellow) star shows it’s being followed.

### Screenshots

![image-5](https://user-images.githubusercontent.com/15748883/177801210-29a5ac14-d17d-4839-86ee-24ea9186e085.jpeg)
![user-profil-non-cliq-member](https://user-images.githubusercontent.com/15748883/177801228-8c4a5458-6e02-4aad-a1b8-2f3f62538e55.png)

https://user-images.githubusercontent.com/15748883/179510443-72808fcf-ae3f-452a-8c73-d7258b598783.mp4

**Comment by palepinkdot** [comment]
Changed criteria based on child widget limitations which have been discussed previously at length.,
