### ISSUE TITLE
My Stuff - Click "More" (list view)

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#177]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user when viewing a list and clicking the "More" link I should see the following display.

### Acceptance Criteria

- Back Arrow goes back to My Stuff Page
- Gear Icon (Settings) goes to List Settings Page
- Share icon shares list that is being viewed
- Top Card for the current list includes: List Title, List Description, and Curated By (the users that manage the list)
- List Media Cards include: Media Image, Title, Plus (Add to List) or Plus Minus (Save to List(s)), Status, and Rex.
- Plus or Plus/Minus are justified left
- Rex icon is justified right
- Status Icon is left-justified in the center. All left status center-align.

**PLUS and PLUS/MINUS ICON STATES:**
-if the media in the card has been added to a list the PLUS/MINUS icon will appear
-If the media in the card has not been added to any list managed by the user the PLUS icon will appear. 

**STATUS ICON STATES:**
-If the media in the card has a status, display the current status in text form
-if the media in the card does not have a status, display the status icon.

**REX ICON STATES:**
-If the media in the card has been rexed, display the gradient Rex with the rating
-If the media in the card has not been rexed, display the white rex icon. 

### Exceptions

none

### Screenshots

![my_stuff_-_more_-_list_view](https://user-images.githubusercontent.com/15748883/179512897-7444b09e-ebbd-4026-b821-addc23534cdd.png)

**Comment by palepinkdot** [comment]
The trans parent section at the top needs to be replaced with a solid action bar for the time being because it will saved an enormous amount of time.

**Comment by palepinkdot** [comment]
@BobRoman Plus/minus functionality

**Comment by BobRoman** [comment]
@palepinkdot the plus/minus has NO new functionality it was just a poor attempt at showing an updated state.  Speaking w/ Dara and James we have updated that icon with something that better aligns with the associated action.  The update will be submitted via a new story.  At this time leave what you currently have.
