### ISSUE TITLE
My Stuff - List "Settings"

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#178]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user when I click the Gear Icon (settings) on My Stuff 'page' this modal should be displayed.

### Acceptance Criteria

- Left Arrow goes back to the previous list being viewed
- Title: List Admin
- Form Fields: Name (text), Description (Text Area), Private or Public LIst (Toggle)
- Collaborators: these are users invited to manage the list media items.
- ~~Manage Collaborators Button will allow the user to add/remove collaborators from the list.~~
- Save Button: Save the field data
- Delete Button: Deleted the list (but not the media within the list). Need dialogue on delete, "Are you sure you wish to delete this list?"

### Exceptions

none

### Screenshots

![My_Stuff_-_List_Settings](https://user-images.githubusercontent.com/15748883/179513674-6779e233-878b-4b46-98cd-27302d1599f4.png)

**Comment by palepinkdot** [comment]
Acceptance criteria altered based on development requirements. Will be reviewed in the retrospective.
