### ISSUE TITLE
My Stuff - Edit Profile

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#180]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user when I click the Gear Icon (Settings) on My Stuff page I should see the following.

### Acceptance Criteria

- The user can edit their user image
- The user can enter any text in the text fields/areas but this is not required.

### Exceptions

none

### Screenshots

![Edit_Profile](https://user-images.githubusercontent.com/15748883/179515236-386d7ae6-86e8-4c7a-a22e-8e9f3ca527b3.png)

**Comment by palepinkdot** [comment]
box heights are a little large, pick and choose battles.

**Comment by BobRoman** [comment]
Cannot update photo from this view :  

https://user-images.githubusercontent.com/15748883/182972943-e2487e97-bb55-4d0b-983f-96c0ff7a962b.MP4

**Comment by BobRoman** [comment]
user profile picture should be consistent between screens : 

https://user-images.githubusercontent.com/15748883/182973064-7ce9bf07-3ea5-4514-a5a8-787c2725167c.MP4

**Comment by BobRoman** [comment]
Screen needs to adjust when text input focus is lower on the page - currently if I try to type in my Facebook/social urls the keypad overlays what you're trying to input 

https://user-images.githubusercontent.com/15748883/182973298-35508577-b2a2-423d-ab6a-038a176a0936.MP4
