### ISSUE TITLE
Wrong release date is displayed for shows and movies

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#182]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

: iPhone 11, 15.4.1

### Last Known Working CliqRex version

n/a

### Expected Behavior

As a CR user when I view the details of a show the release date should be accurate.

### Actual Behavior

Release date on detail view of all cards checked (Shows: Wheel of Time, Stranger Things, Last Kingdom) says June 16, 2022 which is wrong. Yesterday, the release date said June 13, 2022 which was also wrong.

### Steps to reproduce

1. Open app (either version)
2. Go to search
3. enter name of show
4. Click card to see detailed view
5. Observe release date

### Screenshots

![806BD01F-52A7-4B59-A981-87D92A70AEF8_1_105_c jpeg](https://user-images.githubusercontent.com/15748883/179517919-f07eff40-ed4c-4301-9315-c8a5fa6bccbf.jpg)

**Comment by palepinkdot** [comment]
"Wrong data" is not being shown. Changed text on TV shows to be "Latest Episode:"
