### ISSUE TITLE
Feature: Media Score on Poster in List Preview

### ISSUE THREAD

**Issue by palepinkdot** [pixaura/cliqrex-main#184]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

Need to figure out the logic behind this before it goes into GitHub, causes slowdowns.

When is the bubble purple?
When is the bubble grey?
When it is purple what is the data source?
When it is grey what is the data source?

### Acceptance Criteria

- Scores are displayed as described by @BobRoman.

### Exceptions

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/55257671/180475629-3d8510b3-ebad-4b1c-b2ff-dd21e2c0b7a6.png)

**Comment by BobRoman** [comment]
@palepinkdot this question is in regards to the individual media items displayed on #176 .   For simplification purposes and app performance we are going to remove ALL (purple & gray) rating circles/bubbles.   Please let me know if you would like us to resubmit that as a new users story for cleanliness & tracking

**Comment by BobRoman** [comment]
appears to have been removed from all lists - thanks!
