### ISSUE TITLE
All lists have a curated partner

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#187]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

By default lists should not have a curation partner.  Curation partners should only appear if added by the list creator.

### Actual Behavior

All  lists (custom & default) have a curation partner.

### Steps to reproduce

1. click my stuff
2. select (more) on any list to see list details. (all lists contain a curator by default)

### Screenshots

https://user-images.githubusercontent.com/15748883/182680374-60b27be4-1bef-4c18-a7a6-9e576cba530f.MP4

**Comment by palepinkdot** [comment]
intended design feature based on the origin commit. tagged as needed.
