### ISSUE TITLE
clicking on custom & default list displays errors for media items

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#188]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

??

### Expected Behavior

When clicking on one of my lists I should see shows that have been added to that list

### Actual Behavior

getting errors when displaying media items

### Steps to reproduce

1. mystuff
2. click on list (custom / default) seeing errors
3.

### Screenshots

https://user-images.githubusercontent.com/15748883/182679045-412337ca-1f0a-48a3-8b8f-18e05815e387.mp4

https://user-images.githubusercontent.com/15748883/182680518-b0476bd5-c9da-4c90-abd5-2d6f564e90f7.MP4

**Comment by palepinkdot** [comment]
This has been fixed.
