### ISSUE TITLE
clicking on Gear Icon on lists does nothing

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#190]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

na

### Expected Behavior

When viewing my lists and clicking on the gear icon I should be able to manage the list.

### Actual Behavior

Nothing happens

### Steps to reproduce

1. click on mystify
2. click on gear icon 

### Screenshots

https://user-images.githubusercontent.com/15748883/182681734-95a586d0-4868-494f-a24a-234162e667ec.mp4

<img width="505" alt="Screen Shot 2022-08-03 at 12 24 48 PM" src="https://user-images.githubusercontent.com/15748883/182681847-4987e31d-bcd5-4251-88e9-28574d66e6f8.png">

**Comment by palepinkdot** [comment]
Cannot reproduce... Are you sure there is something wrong here?

**Comment by BobRoman** [comment]
@palepinkdot - yes, still experiencing the issue... but I may have figured some things out - seems as though the 'hit state' is actually slightly above the icon - -that is my experience for the 'share' feature as well.  I almost have to click just above the list container.

**Comment by palepinkdot** [comment]
fixed
