### ISSUE TITLE
Error on media card after rating

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#191]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

na

### Expected Behavior

after rating a media item only my rating and associated comment should be added to the card.

### Actual Behavior

After rating a media item my rating and comment appeared but so did an error message 

### Steps to reproduce

1. search for media
2. rate
3. error appears

### Screenshots

https://user-images.githubusercontent.com/15748883/182682362-5776051e-db71-405f-a033-dc437134fced.mp4

**Comment by palepinkdot** [comment]
When you initially rated Breakin, Top Gun Maverick, Jurassic World Domination, and Airplane, how did you do that versus Breakin 2 and Star Wars?

**Comment by palepinkdot** [comment]
I cannot reproduce this issue after implementing a small fix (I think?), I couldn't reproduce this beforehand either so its a shot in the dark.

**Comment by BobRoman** [comment]
@palepinkdot - I've tested again and cannot replicate at this time
