### ISSUE TITLE
Rexing Item doesn't close modal after rating

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#192]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

when I rex an item, after rating and leaving a comment and hitting SAVE, the modal should close and update the card.

### Actual Behavior

After saving the modal is cleared out but does not close

Data does appear to be written properly and accurate when the modal is manually closed

### Steps to reproduce

1. search for media item
2. rex media item (rate & comment)
3. hit save  (modal SHOULD Close - but doesn't)

### Screenshots

https://user-images.githubusercontent.com/15748883/182969954-23cfa21b-6c0a-4ffd-9f5b-5d259e82723d.MP4

(sorry the video is a tad long)

**Comment by palepinkdot** [comment]
fixed
