### ISSUE TITLE
List collaborators don't appear consistently

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#193]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

When I add someone to collaborate on a list they should appear in all areas where collaborators are displayed within the list details ( via More & via Gear Settings) display

### Actual Behavior

Collaborators are only displayed on the management screen (Gear) and not when viewing a list details via the 'more' link.    In that scenario the user who is, incorrectly by default a collaborator on all lists, is the only user displayed.   

I added Dara as a collaborator to a list and just the 'default' collaborator is displayed 

### Steps to reproduce

1. click my stuff
2. click gear icon on list (add collaborator) & save
3. click gear again- collaborator is present
4. close settings panel
5. click 'More' the collaborator is not listed at the top of the screen

### Screenshots

https://user-images.githubusercontent.com/15748883/182971472-a61f87af-b53e-4387-81c4-e30660e2bfa1.MP4

**Comment by palepinkdot** [comment]
The "default" collaborator is you and is not incorrectly displayed because if you create a list, you also curate it.

**Comment by palepinkdot** [comment]
![image](https://user-images.githubusercontent.com/55257671/183093225-ec54c3ad-ef58-400d-bb5c-27fdfe9f39c7.png)
fixed
