### ISSUE TITLE
List settings - doesn't preserve existing data

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#195]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

when editing a list (via gear) the current list information should populate the form fields.

### Actual Behavior

Existing list information does not populate the form fields - appears to load 'default' form fields as if adding a new list.

### Steps to reproduce

1. my stuff
2. Click on gear on list (name / description - fields are not accurate)

3. Same experience after updating via the settings panel ( I rename list in video -> test rename)

### Screenshots

https://user-images.githubusercontent.com/15748883/182974718-b92f7f7b-d569-405e-a140-70caa584eb65.MP4

https://user-images.githubusercontent.com/15748883/182974729-62232299-670a-409b-b399-3a5f06d91ed0.MP4

**Comment by palepinkdot** [comment]
This is not a bug, this in Flutters intended design feature, click on it, the current name will appear as a placeholder.

**Comment by palepinkdot** [comment]
![image](https://user-images.githubusercontent.com/55257671/183095032-5354c29b-7be3-4e01-a36a-bd763099b2fa.png)
![image](https://user-images.githubusercontent.com/55257671/183095111-bc50cc1e-a98e-40e3-8316-441bf2839ac6.png)

flipped them around to make it clearer(?)
