### ISSUE TITLE
Feature: Functionality of the Up Next folder

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#197]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

The Up Next folder in My Stuff is supposed to act as the user's *queue* so that the user can add/view what they want to watch/listen to next. The Up Next folder's current functionality is showing your 20 most recently added items. However, this was not the intended function of the Up Next folder. The Up Next folder should appear in My Stuff and be an empty folder that automatically appears in the list of folders when a user attempts to add a show. 

### Acceptance Criteria

- The Up Next folder appears as a card in My Stuff under the In Progress card. (where it currently is in 0.0.18 (1825))
- The Up Next folder automatically appears at the top of the list of folders (above Create New Custom List) whenever a user attempts to add an item to a list. Users will select the Up Next folder if they want to add it to their queue (watch or listen to next)
- The Up Next folder appears at the top of the list of folders in all places a user can add items to a list: the Rex, Search, the detail view, or from a list 
- In My Stuff, the Up Next card retains all items that the user intends to watch/listen to next.
- Once the user changes the status of an item in the Up Next folder to "finished" or "dropped," the item is removed from the Up Next folder (and goes into the Finished or Dropped folder which is currently linked at the bottom of My Stuff.)

### Exceptions

unknown

### Screenshots

![image](https://user-images.githubusercontent.com/101932440/183699560-4952dce7-3c56-46ea-9796-6367598ba9a4.png)

**Comment by palepinkdot** [comment]
The widget you're specifically looking at is ONLY for custom lists. The only way to have it appear on that list is to make it a custom list. I can make this change to automatically give every user a default Custom List of "Up Next" and then it will appear in that list. However, you will lose the trivial acceptance criteria of having it below the "In progress" list.

OR

I can spend several days on this to make it work as you've designed it.

**Comment by DaraOloughlin** [comment]
Put it in as a default custom list.

**Comment by DaraOloughlin** [comment]
Don't see the Up Next folder. Do I have to be a new user?
