### ISSUE TITLE
Feature: Left/Right scrollable lists with clickable items 

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#198]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user, I want to be able to click on each individual item in the My Stuff cards (lists) so it can directly open up the detail view for that item. I also want to be able to scroll left/right on the My Stuff cards so I can see more items quickly. 

### Acceptance Criteria

- My Stuff cards should allow the user to scroll through the items by left/right.
- My Stuff cards should display items so that the last item on the right is only partially seen. This will help the user know it's left/right scrollable.
- My Stuff card items, when clicked, should open up the detail view of the item.

### Exceptions

unknown

### Screenshots

In this screenshot, you can see the partially seen last item on the right in each card list to show that it's left/right scrollable.
![image](https://user-images.githubusercontent.com/101932440/183705598-d61ab4d1-594c-4550-b4ad-45d93d57c9b4.png)

**Comment by palepinkdot** [comment]
Not in original acceptance criteria of #176, if it was modified it was discussed with Bob to not have it included. Having independently scroll-able lists on each of those cards is an incredibly resource intensive operation. While it may not seem like an issue on 1 or 2 lists, when you start considering that the minimum number of lists on any page is 5 - 10 you start introducing many issues which could manifest themselves in a myriad of ways.
