### ISSUE TITLE
Feature: My Stuff > Clickable items lead to detail view

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#199]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user, I want to be able to click on each individual item in the My Stuff cards (lists) so it can directly open up the detail view for that item. 

### Acceptance Criteria

- The individual My Stuff card items, when clicked, should open up the detail view of the item.
- The user should be able to access the detail view of a card by clicking the thumbnail and title when in the List View (My Stuff > "More" on Any Card > Thumbnail or Title ) 
![IMG_094DA7FB61B1-1](https://user-images.githubusercontent.com/101932440/183714185-0d0facdb-d3be-4ab8-ada7-0c877f1cbadc.jpeg)

### Exceptions

unknown

### Related Issues (if applicable)

The detail view is missing the comment and status buttons.
![IMG_A79D21413781-1](https://user-images.githubusercontent.com/101932440/183713615-953af215-74d4-472f-bce5-633f377cf5cc.jpeg)
.

**Comment by palepinkdot** [comment]
That is not what the related issues section is for those are for other issue like #100 or #101. Anyways, "missing" buttons was part of the original design because the buttons were on the list. I will not edit anything on this page until the new design sprint is completed for it.

**Comment by DaraOloughlin** [comment]
Nice job on making the list view thumbnails clickable. However, the other acceptance criteria that was t met is making the individual items in the My Stuff > list cards clickable (to go to the detail view.) I'll try to make sure I include a screen shot for everything. ![image](https://user-images.githubusercontent.com/101932440/183777640-7bb051b8-206e-4e8b-9a83-dd442614e746.jpeg)
![image](https://user-images.githubusercontent.com/101932440/183777649-5909f3b7-afcf-493d-a276-87fd75c11ffc.jpeg)
