### ISSUE TITLE
Feature: [Request] Font change across the app

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#201]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user, I want to see the font that was chosen during the design process so that I can feel the vibe of the app and not run into awkward design elements when the wrong font and styling are combined. 

### Acceptance Criteria

The correct font (called SF PRO) is used across My Stuff, The Rex, Search, The Feed, and My Cliq and matches the font used in the designs.

### Exceptions

The logo uses a font called Rigid Square.

### Screenshots

Compare the tail of the "y" in the title "My Stuff" in both of these images and you will see that the wrong font has been used. 

<img width="416" alt="Screen Shot 2022-08-09 at 3 18 42 PM" src="https://user-images.githubusercontent.com/101932440/183743345-dc6852d5-1487-422d-9590-a3a1abe5f44d.png">

<img width="430" alt="Screen Shot 2022-08-09 at 3 17 05 PM" src="https://user-images.githubusercontent.com/101932440/183743106-9f20ff08-7a41-4ef5-b017-de45ed65d327.png">

**Comment by palepinkdot** [comment]
https://developer.apple.com/forums/thread/89094
https://developer.apple.com/forums/thread/75894

![image](https://user-images.githubusercontent.com/55257671/183746771-f0020725-8c4c-44bf-90dc-7fc25dc39417.png)

Not allowed to use the SF Pro font 
(or any of apples fonts) on non-apple devices. Adding an exception for iOS devices will introduce unnecessary technical debt and future extraneous development.

**Comment by DaraOloughlin** [comment]
Oh wow. Thanks for the info. Can you point me to a list of fonts we have to choose from?

**Comment by palepinkdot** [comment]
> Oh wow. Thanks for the info. Can you point me to a list of fonts we have to choose from?

That's not a good question for me, I wouldn't know.
