### ISSUE TITLE
change subtitles in the list view

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#203]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user, I want the headings and subtitles of the list pages to be consistent and accurate to help me navigate the app. 

### Acceptance Criteria

- Change the subtitle of the In-progress list page to say "Items that are in progress"
- ~~remove the subtitle of the Custom List pages that do not have a description~~
- change the subtitle of the Dropped list page to say "Lost interest in these items before finishing“
- change the subtitle of the Finished list page to say “Items that have been finished”

(see screenshots for each example)

### Exceptions

N/A

### Screenshots

![DF537421-4A87-4351-B3CF-AF1B553C89B7](https://user-images.githubusercontent.com/101932440/183790408-91b2687d-f49c-43e6-847b-12696dd1058a.jpeg)
![7F1A937E-41F4-4BB4-9141-AD0AA7D679F8](https://user-images.githubusercontent.com/101932440/183790410-65c5b7a2-b071-46d7-af30-490a559613fa.jpeg)
![879B7805-FF94-4FC7-BC24-705AA98D6D17](https://user-images.githubusercontent.com/101932440/183790413-7aae95ff-30fa-4989-bee9-a711993d4349.jpeg)
![FF6F1273-14E5-46D0-A4CE-84505DFBFDEA](https://user-images.githubusercontent.com/101932440/183790414-f47e942b-096f-4815-bc39-ff792b9ece6c.jpeg)

**Comment by palepinkdot** [comment]
CustomLists with no description will keep the placeholder text for debugging purposes.
