### ISSUE TITLE
Bug: share list goes to CliqRex home page

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#205]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

iPhone 11 iOS 15.5

### Last Known Working CliqRex version

Unknown 

### Expected Behavior

When I share a custom list, I expect to send a link that includes the items on the list I selected. 

### Actual Behavior

When I share a *custom* list, a link to the CliqRex home page is sent. 

### Steps to reproduce

1. Go to my stuff
2. Click the share link on a custom list 
3. Select sharing type (text message, copy, etc)
4. See the link is to https://home.CliqRex.com

### Screenshots

https://user-images.githubusercontent.com/101932440/184062561-cee2fd5e-644d-4b49-af20-71c77346cd2c.MOV

**Comment by palepinkdot** [comment]
Once again, not a bug. This is a placeholder, when we actually work on sharing and its we work, the links will work.
