### ISSUE TITLE
Feature: How items appear and sort in the Rex

### ISSUE THREAD

**Issue by stuffthatspins** [pixaura/cliqrex-main#206]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

Keeping the Rex Fresh and Filled with content

Display Criteria: The 3 actions that a user would perform on an item that displays it in the rex are:
- Status changed to "In Progress"
- User Rated
- Top-Level Comment Made (not a reply)

Items will not disappear from the Rex. The logic is for NEW ITEMS display criteria items to display at the top based on time. 

### Acceptance Criteria

- ~~Items remain in the rex. they do not disappear from the rex if the user performs an action on them. which appears to be the current model.~~
- Items stay in the rex and are sorted by newest Display Criteria first. 
- "load more" at every ~~20~~10 items (this appears to be the current functionality)
- ~~the same card should not be repeated.~~

### Exceptions

n/a

### Related Issues (if applicable)

~~this is a much simpler iteration of Issue #114~~

### Screenshots

What we don't want to happen. Since I rated each item in the Rex they disappeared upon reload. We want the rex to keep the items and sort by newest display criteria first. 
https://user-images.githubusercontent.com/4133845/184063278-d96b9a8a-9fee-45d2-8a57-d3afc7b61dca.MP4

**Comment by palepinkdot** [comment]
This is a really round about way to say "Don't remove rated from a users recommendations."

**Comment by DaraOloughlin** [comment]
@palepinkdot Yeah, don't remove 'rated' items from a user's recommendations - but also don't remove 'commented', 'status-updated', or 'added-to-folder' items from a user's recommendations. This screen recording shows how updating the status removes the item from the Rex. Thanks!
![Uploading 184218518...]
