### ISSUE TITLE
Feature: bottom of the media card - remove pill outline

### ISSUE THREAD

**Issue by stuffthatspins** [pixaura/cliqrex-main#208]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR User, I want to see the Status Icon with the appropriate status text so I can see the current status on each card.

This functionality is currently working properly. However, we would like to remove the blue outline "pill" from around the status update text. How the status updates appear in My Stuff -> Any List -> "More" look ideal. This is just the status icon _ text.  

### Acceptance Criteria

-remove the blue outline from the updated status on the bottom of the card
-display the status icon - no need to change the color 
-display the status update "In Progress" "Dropped" or "Finished" next to the icon. (see "status display with text.png"

### Exceptions

n/a at this time. 

### Screenshots

![status display with text](https://user-images.githubusercontent.com/4133845/184066769-307667d9-78dc-47de-8fb8-3934dee31474.png)
![card-remove-blue bill](https://user-images.githubusercontent.com/4133845/184066855-f8e05593-32c7-4c2d-9599-d8ab0adcbe62.jpeg)
![mystuff- move- clean status](https://user-images.githubusercontent.com/4133845/184066859-7070d3c5-f44d-4d21-88cc-82f00c3c1bbe.jpeg)

**Comment by DaraOloughlin** [comment]
Two acceptance criteria have not been met: 

- remove the blue (pill) outline from the updated status on the bottom of the card
- display the status icon (not the check mark) - no need to change the color

**Comment by palepinkdot** [comment]
was changed in a spot w/ dead code.
