### ISSUE TITLE
Feature: Add collaborative folder section 

### ISSUE THREAD

**Issue by DaraOloughlin** [pixaura/cliqrex-main#219]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

As a CR user, I want to be able to see any folders I collaborate with others on so that I can add to them or view them.

### Acceptance Criteria

- In My Stuff, a "Collaborative Folder" section appears below "My Folders" (custom folders) and above "Followed." It's OK if Collaborative Folders need to be a part of My/Custom Folders instead of its own section.
- Collaborative Folders have the "cliq" icon before the title of the folder in My Stuff folder cards (see screenshot)
- The cliq icon appears in front of the name of the collaborative folder in the modal "add to my stuff" - found in the rex, search, a list, or detail view (see screenshot)

### Exceptions

no

### Screenshots
![collab-folder](https://user-images.githubusercontent.com/4133845/184569262-b01d1bcd-8045-4b9f-96fc-563ccd7dc9b7.png)

![Screen Shot 2022-08-11 at 10 41 54 PM](https://user-images.githubusercontent.com/101932440/184275435-3f54f885-bbe2-4d7a-a189-bd70785b88e7.jpeg)

**Comment by palepinkdot** [comment]
Was this a part of the original design? If so, why was it never pushed though?

**Comment by DaraOloughlin** [comment]
The idea of collaborative lists has been in existence a long time. However, not including it as a specialized section of folders was an oversight - something we realized that we missed.
