### ISSUE TITLE
Feature: [request] change home.cliqrex.com to www.cliqrex.com

### ISSUE THREAD

**Issue by stuffthatspins** [pixaura/cliqrex-main#223]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.

### Description

as a website visitor i want the browser url sub-domain to be "www" and not "home"

please let me know before you do this change so I can get setup on siteground. 

### Acceptance Criteria

when going to cliqrex.com redirect non app requests (shares, shows, lists, etc...) to www.cliqrex.com

301 redirect ALL home.cliqrex.com urls to www.cliqrex.com. Regex should work. 

https://home.cliqrex.com/why-cliqrex/ goes to https://www.cliqrex.com/why-cliqrex/

in apache, it'd be something like this:

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_HOST} ^cliqrex.com$ [NC,OR]
  RewriteCond %{HTTP_HOST} ^home.cliqrex.com$
  RewriteRule (.*)$ http://www.cliqrex.com/$1 [R=301,L]
</IfModule>

### Exceptions

n/a

**Comment by palepinkdot** [comment]
They already do, you need to update siteground.

![image](https://user-images.githubusercontent.com/55257671/184643370-3c6bfc8a-bd06-43db-8c73-982600ac6764.png)
