### ISSUE TITLE
Bug: The Rex CliqRex and AppRex

### ISSUE THREAD

**Issue by stuffthatspins** [pixaura/cliqrex-main#226]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain

### What platform are you using?

iOS App

### Operating System Version

iOS 15.5

### Last Known Working CliqRex version

~~0.0.18 (1828)~~

### Expected Behavior

As I CliqRex User I expect shows rated by other users in my cliq to appear in The Rex: Explore CliqRex and AppRex.

**From James' Account**
Dara (in  james' Cliq) rated The Sopraos a 9.0. 
The Sopranos is still not in James' TheRex -> CliqRex or AppRex.

Note: James can see  The Sopranos in the Activity Feed so it is getting saved and visible. 
Dara rated other and they still don't appear in James' The Rex -> CliqRex or AppRex, Hollywood Squares, Little House on the Prairie, and The Office to name a few. 

**From Dara's Account**
James rated Green Acres a 9.0 and Dara does not see this show in her The Rex -> CliqRex.

### Actual Behavior

Newly Rated items do not appear in The Rex -> CliqRex or AppRex. The items are not being sorted by newest rated first. 

### Steps to reproduce

Steps:
1. Have a user in your Cliq rate a Show XYZ
2. Wait >15 minutes
3. Check The Rex -> CliqRex for the Show XYZ
4. Check The Rex -> AppRex for the Show XYZ

### Screenshots

https://user-images.githubusercontent.com/4133845/184765824-c80253bb-d5bf-4c0f-9b9f-cc4794477307.MP4

Uploading dara-cliqrex-does-not-see-green-acres-aug-14-2038.MP4…

**Comment by palepinkdot** [comment]
![image](https://user-images.githubusercontent.com/55257671/184896663-d4495e8f-b25e-4f4a-a303-1083e40a36c6.png)
works now

**Comment by DaraOloughlin** [comment]
Still not working properly. All ratings shown in the Activity Feed should be also showing in the Rex: CliqRex, with most recent first.
