### ISSUE TITLE
Flag a Comment

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#229]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a 

### Description

As a CR user I want to be able to flag an individual comment for either being inappropriate or a spoiler

### Acceptance Criteria

- [x] user should be able to flag an individual comment
- [x] modal overlay should be displayed
- [x] user should be able to submit feedback ~~on the comment~~ if 'other' is selected 
- [x] ~~if~~ feedback ~~is related to REPORTING COMMENT - that information should be~~ immediately emailed to system admins and logged at a system level for future action. 
- [x] if comment is labeled as a spoiler it should be tagged as such ~~and filtered accordingly on the comment detail screen~~ unrelated 

### Exceptions

n/a

### Related Issues (if applicable)

n/a

### Screenshots

![comment_flag](https://user-images.githubusercontent.com/15748883/185149901-c292c770-77fb-42c6-a47c-815fc626aee2.png)

**Comment by palepinkdot** [comment]
@BobRoman have the actual reasons for reporting been thought through? I.E. - Not copied from another app. I don't think terrorism or hate speech won't appear on Ted Lasso from a bunch of 30-45s.

**Comment by palepinkdot** [comment]
@pixaura/cliqrex-product Same thing here with the checkboxes, please decide on  a design.
