### ISSUE TITLE
Edit Comment

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#230]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a

### Description

As a CR user I should be able to edit a comment I created

### Acceptance Criteria

- [x] user should be able to edit a comment they created
- [x] user should be able to tag a comment they created as a spoiler and filtered accordingly on the comment detail screen 
- [x] user should be able to delete a comment they created
- [x] clicking save or the 'back arrow' would return the user to the detail screen 

### Exceptions

n/a

### Related Issues (if applicable)

n/a

### Screenshots

![comment_edit-delete](https://user-images.githubusercontent.com/15748883/185150263-9dcc664e-e404-4e62-96df-253c679ae24f.png)

**Comment by palepinkdot** [comment]
> clicking save or the 'back arrow' would return the user to the detail screen

this functionality is kinda all over the place with modals, some times you've got an X in the corner of the modal, sometimes nothing at all, and now this one. We need to stick with it a consistent functionality for modularity, minimizing bloat, and reducing technical debt (and not adding it)
