### ISSUE TITLE
Comment Detail Screen

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#231]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a

### Description

As a CR user when I click on a  comment from the media detail screen I should see the comment detail screen with associated comments

### Acceptance Criteria

- [x] comments should be displayed in chronological order (newest at top) 
- [x] comments should be truncated 10 lines and utilize the 'read more' functionality 
- [x] user should be able to toggle 'show spoilers' which would remove / hide any comments that are tagged as spoilers 
-  individual commments should include : 
- - [x] users avatar photo, if they are my cliq their affinity ring should be shown in full color
- - [x] display 'timestamp' of comment
- comment functionality 
- -[x]  user should be able to like (HEART) a comment - which ~~will~~ **can** promote it on the media detail screen
- - ~~user should be able to flag a comment or reply~~ **not relevant to this issue**
- - [x] user should be able to reply to a ~~comment~~ **parent comment** ~~(1 level deep)~~, **but not child comments**
- - [x] user should be able to edit a comment they created (see pencil on 1st comment)

### Exceptions
- ~~users avatar photo, if they are my cliq their affinity ring should be shown in gray scale~~ **see other issue**
n/a

### Related Issues (if applicable)

- comment flag #229  
- edit comment #230

### Screenshots

![comment_card_default](https://user-images.githubusercontent.com/15748883/185151068-00eff770-f056-4d3b-93cb-eecbe9db450f.png)

**Comment by palepinkdot** [comment]
> comments should be displayed in chronological order (newest at top)

can we just keep the same sorting from the preview? adding a separate function increases load on the device and is a totally separate read to firebase.

**Comment by palepinkdot** [comment]
> users avatar photo, if they are my cliq their affinity ring should be shown in gray scale

I don't think this is going to make it in, nowhere else is this used, and there isn't an elegant way to introduce this without adding technical debt & bloat. @BobRoman
