### ISSUE TITLE
Comment Display Rules on Media Detail Screen

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#232]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a

### Description

As a CR user when I see comments on the media detail screen they should be based on the following 'rules'

### Acceptance Criteria

- [x] detail screen should display comments related to media item if they exist 
- [x] if no comments exist section should collapse and not be displayed
- [x] comments should be limited to 3 total and truncated at 2 lines each
- [x] comments should  display: the user avatar & name who left the comment & 'timestamp'
-  [x]  if commenter is in my cliq their affinity ring should be displayed (in full color)

comment display priority rules
-  [x] display top 3 comments with most 'likes' (hearts clicked on comment detail screen) 
-  [x] if no comments have been 'liked' display the most recent 
-  [ ] ~~if a only 1 or 2 comments have been liked display them (based on most likes first) then fill the remaining slot(s) with the newest comments~~ Increases loading time and requires processing, by rating OR if none are rated, then time.
-  [x] clicking on view all # comments should load the comments detail screen ~~at the top so the user can view them in chronological order~~ **to see all the comments**
-  [x] to the left of the leave a comment box should display my current profile picture
-  [x] clicking into the leave a comment text input should display the comment detail screen w/ the text input section in focus

### Exceptions
-  [x] if commenter is NOT in my cliq ~~their affinity ring should be displayed in grayscale~~ will be denoted by NOT having a icon next to their name
- [x] #235

### Related Issues (if applicable)

n/a

### Screenshots

![media_detail – 1](https://user-images.githubusercontent.com/15748883/185152708-49272c58-a971-45ae-ac5f-48fabdecf280.png)

**Comment by palepinkdot** [comment]
> if commenter is NOT in my cliq their affinity ring should be displayed in grayscale
 
same thing as #231 @BobRoman
