### ISSUE TITLE
Media Detail Screen Redesign

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#234]
### Avoid Duplicates

- [X] I have searched the [issue tracker](https://github.com/pixaura/cliqrex-main/issues), without success.
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a

### Description

As a CR user when I click on a media item I should be presented with the following media detail screen and functionality 

### Acceptance Criteria

- [X] screen should display media title above poster image
- [X] media detail poster / detail image should load 
- ~~clicking on play button on top of media detail should play the 'trailer' or audio intro /equivalent~~
- ~~clicking on play button should use system controls and default players to display the media element(s)~~
- [X] if members of my cliq have rated the media item, their average rating should be displayed in the purple dot overlaying the media poster image
- [X] if no-one from my cliq has rated the media item, it should NOT display a rating at all
- ~~when I click on the STAR above the media poster image should add that to my favorites list (and follow associated protocol / rules)~~
- [X] when I click on the SHARE icon - I should be able to share this media item via the standard share capabilities based on device
- [X] beneath poster image display TV Rating (G,PG, TV-MA etc...)
- [X] beneath poster image display global rating as determined by 3rd party sounces
- [X] description of media item should be displayed beneath the ratings and truncated to 3 lines w/ a read more button
- [X] clicking on the 'read more' button beneath the media description should expand and display the entire description pushing the remaining page content down
- [X] screen should display Genres associated with media item
- [X] detail screen should display what network the media item is available on
- [X] clicking on any of available networks should direct the user to that media item within it's provided source 
- [X] detail screen should display the members/cast/curators etc..) and allow for L->R->L scrolling
- [X] the ~~'bottom nav bar'~~ footer (list, comment, status, rex) should be pinned to the bottom of the viewport and function as it - does on the media card with in the REX (please follow up with questions)

### Exceptions

n/a

### Related Issues (if applicable)

- cliq members on detail screen #233 
- comment display rules on detail screen #232
- comment details #231

### Screenshots

![media_detail – 1](https://user-images.githubusercontent.com/15748883/185154957-c7f33989-ddf9-45b7-a080-6d14a0126371.png)

https://user-images.githubusercontent.com/15748883/185155316-b4643b3e-924e-4f28-a837-9b0d85af2a84.mp4

**Comment by palepinkdot** [comment]
RE: Star icon

This feature does not exist anywhere else and its existence is implied from the acceptance criteria. Create a separate issue for this so called 'favorites' list. Acceptance criteria have been altered to account for this.

**Comment by palepinkdot** [comment]
RE: click to play  trailer

This needs to be broken out to its own issue. This feature does not exist yet and is not as simple as "just use the built in players." This separate issue can also get quite complicated given we do not have the rights to show trailers on a for-profit app. If a trailer is longer than 30 seconds, it falls outside of fair-use and as such is subject to copyright infringement. Think this through a bit more and create a separate issue once all of the problems have bee solved. Acceptance criteria have been altered accordingly.

**Comment by DaraOloughlin** [comment]
@palepinkdot the trailer can just go to YouTube to play like it did in previous versions. It does not need to play in-app.
