### ISSUE TITLE
Bug iOS: Media Detail Screen missing detailed information

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#239]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

https://trello.com/c/tONCwHhK/66-2022004-234-detail-page-networks-are-missing

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

related to build 2022.004

### Expected Behavior

Media detail screen should network info:  display Netflix, HBO etc.

### Actual Behavior

missing information on screens

### Steps to reproduce

1. goto media detail screen 

### Screenshots

![image](https://user-images.githubusercontent.com/15748883/187706213-9446a3d8-af0d-47da-8609-b2699003b77a.png)

**Comment by palepinkdot** [comment]
ios issue
