### ISSUE TITLE
Comment Order

### ISSUE THREAD

**Issue by BobRoman** [pixaura/cliqrex-main#241]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain
- [X] This issue has been approved/reviewed on Trello by @BobRoman

### Trello Link

n/a

### What platform are you using?

iOS App

### Operating System Version

15.5

### Last Known Working CliqRex version

n/a

### Expected Behavior

when leaving a comment the most recent comment should appear at the bottom of the comment stream.

### Actual Behavior

comment appears (hard to really tell due to the limited # of users ) in the middle of the comments display

### Steps to reproduce

1. click to media detail 
2. leave comment 
3. appears in 'random' location for me

### Screenshots

![IMG_4147](https://user-images.githubusercontent.com/15748883/187822893-f2a0c02c-8641-465e-9157-db0bfcacc25d.PNG)
![IMG_4149](https://user-images.githubusercontent.com/15748883/187822909-e1341ccf-94bc-4a1c-ac5e-0237c55b5aa4.PNG)

### Additional information

n/a

**Comment by palepinkdot** [comment]
From #232 

>  if a only 1 or 2 comments have been liked display them (based on most likes first) then fill the remaining slot(s) with the newest comments

This is what is happening here.
