### ISSUE TITLE
[Request]: Ad System

### ISSUE THREAD

**Issue by palepinkdot** [pixaura/cliqrex-main#30]
From cliqrex-site created by [stuffthatspins](https://github.com/stuffthatspins): pixaura/cliqrex-site#23  

null

**Comment by palepinkdot** [comment]
The ability to purchase ads and display them in the app. Ads purchased based on CPM.

notify ad buyer with distribution info/charts.

**Comment by stuffthatspins** [comment]
https://www.is.com/

**Comment by palepinkdot** [comment]
https://console.firebase.google.com/project/cliqrex/admob

Why pay extra for is
