### ISSUE TITLE
[Bug]: search and add. 

### ISSUE THREAD

**Issue by stuffthatspins** [pixaura/cliqrex-main#64]
### Contact Details

effort@gmail.com

### What happened?

Search for a show. Bad vegan for example.  The first time you try to add it just a note shows up. Can't select any lists. 

### What platforms are you seeing the problem on?

Mobile

### Version

No clue

### Make sure you have read the Contribution Guidelines.

- [X] I have read the Contribution Guidelines.

**Comment by palepinkdot** [comment]
https://user-images.githubusercontent.com/55257671/159356220-74cc62e9-c187-4eba-a098-5377a9dffba6.MOV

Cannot recreate. Please see video. Placing on hold until further notice.

**Comment by palepinkdot** [comment]
Occurred again with #77.

**Comment by palepinkdot** [comment]
https://user-images.githubusercontent.com/55257671/159492249-77cfcc72-dc7c-4d2a-9a2a-5a0e12ef8c17.mp4

Attempted re-creation with users' account cloned into a test account. See attached video for test.
